# frozen_string_literal: true

##
#
module JABA

  using JABACoreExt
  
  ##
  # Base class for instances of projects, where a 'project' is anything generated by a generator. This could
  # therefore be the base class for a Visual Studio project, an Xcode project, a makefile, a workspace etc,
  # or anything else that Jaba is made to generate.
  #
  class Project
    
    attr_reader :node
    attr_reader :attrs
    
    ##
    #
    def initialize(generator, node)
      @generator = generator
      @node = node
      @attrs = node.attrs
    end
    
    ##
    #
    def services
      @generator.services
    end

    ##
    # eg MyApp|vs2019|windows
    #
    def handle
      @node.handle
    end

    ##
    # Override this in subclass.
    #
    def generate
      # nothing
    end

    ##
    # Override this in subclass.
    #
    def build_jaba_output(p_root, out_dir)
      # nothing
    end

  end

end
