# frozen_string_literal: true

# This file deals with invoking Jaba, whether running standalone or embedding in other code
#
require_relative 'core/services'

##
#
module JABA

  using JABACoreExt

  ##
  #
  def self.run
    s = Services.new
    yield s.input if block_given?
    s.run
  end

  ##
  # Input to pass to Jaba.
  #
  class Input
    
    ##
    # One or more filenames and/or directories from which to load definitions.
    #
    attr_accessor :load_paths
    
    ##
    #
    attr_block :definitions
    
    ##
    # Logging is disabled by default for performance.
    #
    attr_bool :enable_logging
    
  end

  ##
  # Output from Jaba, returned by JABA.run.
  #
  class Output

    ##
    # Array of files generated by this run of JABA.
    #
    attr_reader :generated_files
    
    ##
    # Array of any warnings that were generated.
    #
    attr_reader :warnings
    
  end

  ##
  # Raised when there is an error raised from inside Jaba, either from the user definitions or from internal library
  # code.
  #
  class JabaError < StandardError
    
    ##
    #
    attr_reader :raw_message
    
    ##
    # True if error is an internal error as opposed to a user error in the definitions.
    #
    attr_reader :internal
    
    ##
    # The definition file the error occurred in. Not available if definitions were executed as a block.
    #
    attr_reader :file
    
    ##
    # The line in the definition file that the error occurred at. Not available if definitions were executed as a block.
    #
    attr_reader :line
    
  end

  ##
  #
  class TopLevelAPI < BasicObject
    
    ##
    # Define a project.
    #
    def project(id, **options, &block)
      @services.define_instance(:project, id, **options, &block)
    end
    
    ##
    # Define a workspace.
    #
    def workspace(id, **options, &block)
      @services.define_instance(:workspace, id, **options, &block)
    end
    
    ##
    # Define a category.
    #
    def category(id, **options, &block)
      @services.define_instance(:category, id, **options, &block)
    end
    
    ##
    # Define definition to be included by other definitions.
    #
    def shared(id, **options, &block)
      @services.define_instance(:shared, id, **options, &block)
    end
    
    ##
    #
    def text(id, **options, &block)
      @services.define_instance(:text, id, **options, &block)
    end
    
    ##
    # All undefined methods are treated as defining instances of jaba types.
    #
    def method_missing(type, id, **options, &block)
      @services.define_instance(type, id, **options, &block)
    end
    
    ##
    # EXTENSION API
    #
    def attr_type(id, &block)
      @services.define_attr_type(id, &block)
    end
    
    ##
    # EXTENSION API
    #
    def attr_flag(id)
      @services.define_attr_flag(id)
    end
    
    ##
    # EXTENSION API
    #
    def define(type, **options, &block)
      @services.define_type(type, **options, &block)
    end
    
    ##
    # EXTENSION API
    #
    def open(type, &block)
      @services.open_type(type, &block)
    end
    
    ##
    #
    def initialize(services)
      @services = services
    end
    
  end

end

if $PROGRAM_NAME == __FILE__
  begin
    JABA.run do |j|
      j.load_paths = Dir.getwd
      j.enable_logging = ARGV.delete('--log') ? true : false
    end
  rescue JABA::JabaError => e
    puts e.message
    puts 'Backtrace:'
    puts(e.backtrace.map {|line| "  #{line}"})
  end
end
